import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add Dashboard CSS before </style>
css_patch = """
    /* DASHBOARD VIEW */
    .dashboard-view { padding: 40px 24px; max-width: 1000px; width: 100%; margin: 0 auto; flex: 1; }
    .section-title { font-size: 20px; font-weight: 800; margin-bottom: 24px; color: var(--text); margin-top: 32px;}
    .grid-recents { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }
    .set-card {
      background: var(--card-bg); border: 2px solid var(--border); border-radius: 16px;
      padding: 18px; display: flex; align-items: center; gap: 16px; cursor: pointer;
      transition: all 0.2s; box-shadow: 0 4px 0 0 transparent;
    }
    .set-card:hover { transform: translateY(-4px); border-color: var(--primary); box-shadow: 0 4px 0 0 var(--primary-hover); }
    .set-card-icon { width: 44px; height: 44px; border-radius: 8px; background: var(--primary-light); color: var(--primary); display: flex; align-items: center; justify-content: center; font-size: 20px; flex-shrink: 0; }
    .set-card-info { flex: 1; overflow: hidden; }
    .set-card-title { font-weight: 800; font-size: 16px; margin-bottom: 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .set-card-meta { font-size: 12px; font-weight: 700; color: var(--text-muted); }
    
    #study-view { display: flex; flex-direction: column; flex: 1; }
</style>"""
content = content.replace("</style>", css_patch)

# 2. Add Dashboard HTML right after </header>
html_patch = """</header>
  
  <div id="dashboard-view" class="dashboard-view">
    <h2 class="section-title">Jump back in / Gần đây</h2>
    <div id="dashboard-grid" class="grid-recents">
      <!-- Generated by JS -->
    </div>
  </div>

  <div id="study-view" style="display: none;">
"""
content = content.replace("</header>", html_patch)

# Wrap sub-bar and main in study-view
content = content.replace("</main>\n\n  <!-- MODAL MANUAL -->", "</main>\n  </div>\n\n  <!-- MODAL MANUAL -->")

# 3. Change logo click to go to dashboard
content = content.replace('onclick="window.location.reload()"', 'onclick="showDashboard()"')

# 4. Add JS to render dashboard
js_patch = """
    function showDashboard() {
      document.getElementById('study-view').style.display = 'none';
      document.getElementById('dashboard-view').style.display = 'block';
    }
    
    function renderDashboard(sets) {
      const grid = document.getElementById('dashboard-grid');
      grid.innerHTML = '';
      sets.forEach(s => {
        const div = document.createElement('div');
        div.className = 'set-card';
        div.onclick = () => {
          document.getElementById('set-select').value = s.id;
          onSetChange(s.id);
        };
        div.innerHTML = `
          <div class="set-card-icon">🗂️</div>
          <div class="set-card-info">
            <div class="set-card-title">${s.title}</div>
            <div class="set-card-meta">${s.numTerms} cards ${s.isCustom ? '· by you' : ''}</div>
          </div>
        `;
        grid.appendChild(div);
      });
    }
"""
content = content.replace("let customSetsData = [];", "let customSetsData = [];" + js_patch)

# 5. Modify loadSetsList to call renderDashboard
render_call = """
      // Populate select UI
      select.innerHTML = "";
      const combinedSets = [...allSets, ...customSets];
      renderDashboard(combinedSets);
      
      const optgroupGlobal = document.createElement("optgroup");
"""
content = content.replace('const optgroupGlobal = document.createElement("optgroup");', render_call)

# 6. Modify onSetChange to show study view
onset_patch = """
    async function onSetChange(setId) {
      document.getElementById('dashboard-view').style.display = 'none';
      document.getElementById('study-view').style.display = 'flex';
"""
content = content.replace("async function onSetChange(setId) {", onset_patch)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("Patched index.html successfully.")
